# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: PR made against main

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  PR_against_main:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: clean install all dependencies
      run: npm install
    - name: run unit tests, lint and build the project
    # By running the pr-checks npm script we can change the behaviour of what checks we're running easily in the package.json
      run: npm run pr-checks